# Generated by Django 5.1.5 on 2025-10-03 04:01

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "marca",
                    models.CharField(blank=True, max_length=255, verbose_name="Marca"),
                ),
                (
                    "modelo",
                    models.CharField(blank=True, max_length=255, verbose_name="Modelo"),
                ),
                (
                    "tipo",
                    models.CharField(blank=True, max_length=255, verbose_name="Tipo"),
                ),
                (
                    "palabras_claves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Palabras Clave",
                    ),
                ),
                (
                    "familia",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Familia"
                    ),
                ),
                (
                    "sub_familia",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Sub Familia"
                    ),
                ),
                (
                    "material_principal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Material Principal"
                    ),
                ),
                (
                    "material_secundario",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Material Secundario"
                    ),
                ),
                (
                    "codigo_fabricante",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Código Fabricante"
                    ),
                ),
                (
                    "especificacion_tecnica",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Especificación Técnica"
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Tags",
                    ),
                ),
                (
                    "industria",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Industria"
                    ),
                ),
                (
                    "url_ficha_tecnica",
                    models.URLField(blank=True, verbose_name="URL Ficha Técnica"),
                ),
                (
                    "url_manual_tecnico",
                    models.URLField(blank=True, verbose_name="URL Manual Técnico"),
                ),
                (
                    "url_imagen_principal",
                    models.URLField(blank=True, verbose_name="URL Imagen Principal"),
                ),
                (
                    "nivel_uso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOMESTICO", "Doméstico"),
                            ("COMERCIAL", "Comercial"),
                            ("INDUSTRIAL", "Industrial"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Nivel de Uso",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("DESCONTINUADO", "Descontinuado"),
                            ("PENDIENTE_APROBACION", "Pendiente de Aprobación"),
                        ],
                        default="PENDIENTE_APROBACION",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "peso_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Peso",
                    ),
                ),
                (
                    "peso_unidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("G", "Gramos"),
                            ("KG", "Kilogramos"),
                            ("TON", "Toneladas"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Unidad de Peso",
                    ),
                ),
                (
                    "largo_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Largo",
                    ),
                ),
                (
                    "largo_unidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MM", "Milímetros"),
                            ("CM", "Centímetros"),
                            ("DM", "Decímetros"),
                            ("M", "Metros"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Unidad de Largo",
                    ),
                ),
                (
                    "alto_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Alto",
                    ),
                ),
                (
                    "alto_unidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MM", "Milímetros"),
                            ("CM", "Centímetros"),
                            ("DM", "Decímetros"),
                            ("M", "Metros"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Unidad de Alto",
                    ),
                ),
                (
                    "ancho_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Ancho",
                    ),
                ),
                (
                    "ancho_unidad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MM", "Milímetros"),
                            ("CM", "Centímetros"),
                            ("DM", "Decímetros"),
                            ("M", "Metros"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Unidad de Ancho",
                    ),
                ),
                (
                    "categoria_lvl1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Categoría Nivel 1"
                    ),
                ),
                (
                    "categoria_lvl2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Categoría Nivel 2"
                    ),
                ),
                (
                    "categoria_lvl3",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Categoría Nivel 3"
                    ),
                ),
                (
                    "categoria_lvl4",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Categoría Nivel 4"
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo",
                "verbose_name_plural": "Artículos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "razon_social",
                    models.CharField(
                        blank=True,
                        max_length=765,
                        null=True,
                        verbose_name="Razón Social",
                    ),
                ),
                (
                    "localizacion",
                    models.TextField(blank=True, verbose_name="Localización"),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="CUIT",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("PENDIENTE_APROBACION", "Pendiente de Aprobación"),
                        ],
                        default="ACTIVO",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                ("web_page", models.URLField(blank=True, verbose_name="Página Web")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre de Contacto"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono de Contacto"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de Contacto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Despachante",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=765, verbose_name="Razón Social"),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="CUIT",
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "telefono_secundario",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Secundario"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nombre de Contacto"
                    ),
                ),
                (
                    "email_secundario",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Secundario"
                    ),
                ),
            ],
            options={
                "verbose_name": "Despachante",
                "verbose_name_plural": "Despachantes",
                "ordering": ["razon_social"],
            },
        ),
        migrations.CreateModel(
            name="FormaDeEntrega",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Forma de Entrega",
                "verbose_name_plural": "Formas de Entrega",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "razon_social",
                    models.CharField(max_length=765, verbose_name="Razón Social"),
                ),
                (
                    "localizacion",
                    models.TextField(blank=True, verbose_name="Localización"),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        unique=True,
                        verbose_name="CUIT",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("PENDIENTE_APROBACION", "Pendiente de Aprobación"),
                        ],
                        default="PENDIENTE_APROBACION",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "es_proveedor_nacional",
                    models.BooleanField(
                        default=False, verbose_name="Proveedor Nacional"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProveedorFormaEntrega",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Proveedor-Forma de Entrega",
                "verbose_name_plural": "Proveedores-Formas de Entrega",
            },
        ),
    ]
