# Generated by Django 5.1.5 on 2025-10-03 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="despachante",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="despachante",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="despachante",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="formadeentrega",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="formadeentrega",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="formadeentrega",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedorformaentrega",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedorformaentrega",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="proveedorformaentrega",
            name="forma_entrega",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proveedores",
                to="core.formadeentrega",
                verbose_name="Forma de Entrega",
            ),
        ),
        migrations.AddField(
            model_name="proveedorformaentrega",
            name="proveedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formas_entrega",
                to="core.proveedor",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="proveedorformaentrega",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_actualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actualizado por",
            ),
        ),
        migrations.AddIndex(
            model_name="articulo",
            index=models.Index(fields=["status"], name="idx_articulos_status"),
        ),
        migrations.AddIndex(
            model_name="articulo",
            index=models.Index(fields=["familia"], name="idx_articulos_familia"),
        ),
        migrations.AddIndex(
            model_name="articulo",
            index=models.Index(fields=["marca"], name="idx_articulos_marca"),
        ),
        migrations.AddIndex(
            model_name="articulo",
            index=models.Index(
                fields=["categoria_lvl1"], name="idx_articulos_categoria_lvl1"
            ),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["cuit"], name="idx_clientes_cuit"),
        ),
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(fields=["status"], name="idx_clientes_status"),
        ),
        migrations.AddIndex(
            model_name="proveedor",
            index=models.Index(fields=["cuit"], name="idx_proveedores_cuit"),
        ),
        migrations.AddIndex(
            model_name="proveedor",
            index=models.Index(fields=["status"], name="idx_proveedores_status"),
        ),
        migrations.AlterUniqueTogether(
            name="proveedorformaentrega",
            unique_together={("proveedor", "forma_entrega")},
        ),
    ]
