# Generated by Django 5.1.5 on 2025-10-03 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                            ("VIEW", "Ver"),
                            ("APPROVE", "Aprobar"),
                            ("REJECT", "Rechazar"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("id_entidad", models.UUIDField(verbose_name="ID de Entidad")),
                (
                    "tipo_entidad",
                    models.CharField(
                        choices=[
                            ("PROVEEDOR", "Proveedor"),
                            ("CLIENTE", "Cliente"),
                            ("ARTICULO", "Artículo"),
                            ("COTIZACION", "Cotización"),
                            ("ORDEN_COMPRA", "Orden de Compra"),
                            ("PEDIDO_COTIZACION", "Pedido de Cotización"),
                            ("SOLPED", "Solped"),
                            ("REMITO", "Remito"),
                            ("ENVIO", "Envío"),
                            ("USUARIO", "Usuario"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Entidad",
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True, verbose_name="Datos")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Comunicacion",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                ("contenido", models.TextField(verbose_name="Contenido")),
                (
                    "entidad_tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROVEEDOR", "Proveedor"),
                            ("CLIENTE", "Cliente"),
                            ("ARTICULO", "Artículo"),
                            ("COTIZACION", "Cotización"),
                            ("ORDEN_COMPRA", "Orden de Compra"),
                            ("PEDIDO_COTIZACION", "Pedido de Cotización"),
                            ("SOLPED", "Solped"),
                            ("REMITO", "Remito"),
                            ("ENVIO", "Envío"),
                            ("USUARIO", "Usuario"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Entidad",
                    ),
                ),
                (
                    "entidad_id",
                    models.UUIDField(
                        blank=True, null=True, verbose_name="ID de Entidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación",
                "verbose_name_plural": "Comunicaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "margen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Margen (%)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("RECIBIDA", "Recibida"),
                            ("EVALUADA", "Evaluada"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionGanador",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Cotización Ganadora",
                "verbose_name_plural": "Cotizaciones Ganadoras",
            },
        ),
        migrations.CreateModel(
            name="CotizacionProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("RECIBIDA", "Recibida"),
                            ("EVALUADA", "Evaluada"),
                            ("ACEPTADA", "Aceptada"),
                            ("RECHAZADA", "Rechazada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización de Proveedor",
                "verbose_name_plural": "Cotizaciones de Proveedores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CotizacionSolped",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Cotización-Solped",
                "verbose_name_plural": "Cotizaciones-Solpeds",
            },
        ),
        migrations.CreateModel(
            name="DetalleCotizacionProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "precio_unitario_valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "precio_unitario_moneda",
                    models.CharField(
                        default="ARS", max_length=3, verbose_name="Moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cotización de Proveedor",
                "verbose_name_plural": "Detalles de Cotizaciones de Proveedores",
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompraCliente",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "precio_valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio"
                    ),
                ),
                (
                    "precio_moneda",
                    models.CharField(
                        default="ARS", max_length=3, verbose_name="Moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra de Cliente",
                "verbose_name_plural": "Detalles de Órdenes de Compra de Clientes",
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompraProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "precio_unitario_valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "precio_unitario_moneda",
                    models.CharField(
                        default="ARS", max_length=3, verbose_name="Moneda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra a Proveedor",
                "verbose_name_plural": "Detalles de Órdenes de Compra a Proveedores",
            },
        ),
        migrations.CreateModel(
            name="DetallePedidoCotizacionProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido de Cotización a Proveedor",
                "verbose_name_plural": "Detalles de Pedidos de Cotización a Proveedores",
            },
        ),
        migrations.CreateModel(
            name="DetalleRemito",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Remito",
                "verbose_name_plural": "Detalles de Remitos",
            },
        ),
        migrations.CreateModel(
            name="DetalleSolped",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "cantidad_valor",
                    models.DecimalField(
                        decimal_places=3, max_digits=15, verbose_name="Cantidad"
                    ),
                ),
                (
                    "cantidad_unidad",
                    models.CharField(
                        choices=[
                            ("UNIDAD", "Unidad"),
                            ("CAJA", "Caja"),
                            ("PALLET", "Pallet"),
                            ("KG", "Kilogramo"),
                            ("LITRO", "Litro"),
                            ("METRO", "Metro"),
                            ("M2", "Metro Cuadrado"),
                            ("M3", "Metro Cúbico"),
                        ],
                        max_length=10,
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Solped",
                "verbose_name_plural": "Detalles de Solped",
            },
        ),
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "numero_seguimiento",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Número de Seguimiento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREPARANDO", "Preparando"),
                            ("EN_TRANSITO", "En Tránsito"),
                            ("ENTREGADO", "Entregado"),
                            ("DEVUELTO", "Devuelto"),
                            ("PERDIDO", "Perdido"),
                            ("DEMORADO", "Demorado"),
                        ],
                        default="PREPARANDO",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_entrega_real",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Real"
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompraCliente",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Orden",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra de Cliente",
                "verbose_name_plural": "Órdenes de Compra de Clientes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompraProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Orden",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra a Proveedor",
                "verbose_name_plural": "Órdenes de Compra a Proveedores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PedidoCotizacionProveedor",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE DE RESPUESTA", "Pendiente de Respuesta"),
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("RESPONDIDO", "Respondido"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Cotización a Proveedor",
                "verbose_name_plural": "Pedidos de Cotización a Proveedores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PedidoCotizacionSolped",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
            ],
            options={
                "verbose_name": "Pedido Cotización-Solped",
                "verbose_name_plural": "Pedidos Cotización-Solpeds",
            },
        ),
        migrations.CreateModel(
            name="PedidoDeCotizacion",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDIENTE DE RESPUESTA", "Pendiente de Respuesta"),
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("RESPONDIDO", "Respondido"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=25,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido de Cotización",
                "verbose_name_plural": "Pedidos de Cotización",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Remito",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "numero_remito",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Remito",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("EN_TRANSITO", "En Tránsito"),
                            ("ENTREGADO", "Entregado"),
                            ("DEVUELTO", "Devuelto"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Remito",
                "verbose_name_plural": "Remitos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Solped",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "nro_solped",
                    models.IntegerField(unique=True, verbose_name="Número de Solped"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADA", "Enviada"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("EN_PROCESO", "En Proceso"),
                            ("COMPLETADA", "Completada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solped",
                "verbose_name_plural": "Solpeds",
                "ordering": ["-created_at"],
            },
        ),
    ]
